---
name: Validate all listed domains

on:
  #schedule:
  #  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4

      - name: Main Process
        run: bash .github/scripts/check-domains.sh && echo "Done!"

      - name: Commit and push on changes
        run: |-
          git pull
          git add .
          git diff
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "Updated all.txt" -a || echo "No changes to commit"
          git push
